[package]
name = "state-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
take_mut = "0.2.2"
state-machine-macros = { path = "../state-machine-macros" }
itertools = "0.11.0"
